travis:
  secure:
    BINSTAR_TOKEN: kO0IRoHaTltBQfd9xMsfelkO9rjtl0R5lsv9LhmdI7MZUjsqls32NlG0iciRuBsLVl4JIlN6H1TqFgh1PBdK/BiOIs1W0j/Q6TRsDXTSPq/YmoEjJn4EWvM7alpCjjrxjp+hq0mQFShi5sY5yVDdcEOAH8ZYyTFi2PLeQtE21TLxOOm0w3FRGdvjHpyUDa5a+jBlwDdcQMPc9brm8a8+fvpCMnc74Ei/Szr4qI1QsmEc0ftp2VAX/jpE3FkNXZ8qXfwGq24Dx4KBQ9k+NoMnG59HoAAB+Uo03e7czy9RBzUz8HT8wr9FlOmaHjGoQasJmlmpqYYlGYTdt71mXmK6UOM/CV9gY2T4OQ3wHt+7o1tBaUTHCuogy9VRI9vYns5bZhdefZsDNEIqsPaEPSyhPiPTAID1t9lxq/zKhLpKvfd2n8NKQoRoNbc+CTGeppXIMYsHHPFWvFUOO911MJonCXzt9yeKpDXtaROWsYmF0G+O9yLMULwbCZX5e4NZdvyjbo0gFh1VCzuieC8XHXg9hkCK7JxLVGpVCBt8RfB+GY5UJ+i18hz1zjivFixQnHSvu80AFk4+l16lFozBXbw0FVp5TUKALqLzmBLDjts+l+l6/PRk/TqQ4a3o+cVC5Y3dB/yvXWSSmAPgSKSNHIdjtqKtvHHodxpK4lXHf2oC5Eg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
